package vpms.controller;

import vpms.dao.SlotDao;
import vpms.dao.SlotInstanceDao;
import vpms.model.SlotData;
import vpms.view.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.SQLException;
import java.util.List;

/**
 * Lists, adds, edits and deletes slot-collections (rows in table **slots**).
 * Each row represents *all* bays of one vehicle-type on one level.
 */
public class SlotManagementController {

    /* ------------ fields ------------ */
    private final SlotManagementView view;
    // CRUD for “slots”
    private final SlotDao            slotDao;        
//    private final SlotInstanceDao    instanceDao;

    /* ------------ ctor ------------ */
    public SlotManagementController(SlotManagementView view) throws SQLException {
        this.slotDao = new SlotDao();
        this.view = view;
//        this.instanceDao  = new SlotInstanceDao(); // bulkInsert …

        loadSlotTable();                                 // fill table on start-up
        view.getSlotTable().setDefaultEditor(Object.class, null);   // read-only cells
        view.getSlotTable().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        /* hook buttons generated by NetBeans */
        view.addAddButtonListener(new AddListener());
//        view.addEditButtonListener().addActionListener     (e -> new EditListener());
        view.addDeleteButtonListener().addActionListener   (e -> new DeleteListener());
        view.addCancelButtonListener().addActionListener   (e -> loadSlotTable());
        view.addSearchButtonListener().addActionListener   (e -> new SearchListener());
    }

    public void open() { view.setVisible(true); }

    /* ===================================================== *
     *  TABLE REFRESH                                        *
     * ===================================================== */
    private void loadSlotTable() {
        try {
            List<SlotData> rows = slotDao.findAll();           // SELECT *
            DefaultTableModel m = (DefaultTableModel) view.getSlotTable().getModel();
            m.setRowCount(0);
            for (SlotData s : rows) {
                m.addRow(new Object[]{
                        s.getSlot_id(),
                        s.getVehicletandp(),
                        s.getNumber_of_slot(),
                        s.getLevel_number()
                });
            }
        } catch (Exception ex) {
            showError("Cannot load slots.", ex);
        }
    }

    /* ===================================================== *
     *  ADD                                                  *
     * ===================================================== */
    private class AddListener implements ActionListener {
        @Override public void actionPerformed(ActionEvent e) {
            AddSlotView popup = new AddSlotView();
            try {
                System.out.println("Add slot popup");
                new AddSlotController(popup, SlotManagementController.this).open();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    /* ===================================================== *
     *  EDIT                                                 *
     * ===================================================== */
//    private class EditListener implements ActionListener {
//        @Override public void actionPerformed(ActionEvent e) {
//            int row = view.getSlotTable().getSelectedRow();
//            if (row == -1) {
//                JOptionPane.showMessageDialog(view,"Select a slot first."); return;
//            }
//            /* Build SlotData from table */
//            SlotData s = new SlotData(
//                    (int) view.getSlotTable().getValueAt(row,0),
//                    (int) view.getSlotTable().getValueAt(row,1),
//                    (int) view.getSlotTable().getValueAt(row,2),
//                    (int) view.getSlotTable().getValueAt(row,3)
//            );
//            EditSlotView popup = new EditSlotView();                       // similar to AddSlotView
//            new EditSlotController(popup, s, SlotManagementController.this).open();
//        }
//    }

    /* ===================================================== *
     *  DELETE                                               *
     * ===================================================== */
    private class DeleteListener implements ActionListener {
        @Override public void actionPerformed(ActionEvent e) {
            int row = view.getSlotTable().getSelectedRow();
            if (row == -1) { JOptionPane.showMessageDialog(view,"Pick a row."); return; }

            int slotId = (int) view.getSlotTable().getValueAt(row,0);
            if (JOptionPane.showConfirmDialog(view,"Delete slot "+slotId+"?",
                    "Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION) return;

            try {
                if (slotDao.delete(slotId)) {
                    JOptionPane.showMessageDialog(view,"Slot deleted.");
                    loadSlotTable();
                } else {
                    JOptionPane.showMessageDialog(view,"Delete failed – row not found.");
                }
            } catch (Exception ex) { showError("Delete failed.", ex); }
        }
    }

    /* ===================================================== *
     *  SEARCH                                               *
     * ===================================================== */
    private class SearchListener implements ActionListener {
        @Override public void actionPerformed(ActionEvent e) {
            String kw = view.getSearchText().getText().trim().toLowerCase();
            if (kw.isEmpty()) { loadSlotTable(); return; }

            try {
                List<SlotData> all = slotDao.findAll();
                DefaultTableModel m = (DefaultTableModel) view.getSlotTable().getModel();
                m.setRowCount(0);
                for (SlotData s : all) {
                    if ( String.valueOf(s.getSlot_id()).contains(kw) ||
                         String.valueOf(s.getVehicletandp()).contains(kw) ||
                         String.valueOf(s.getLevel_number()).contains(kw)) {
                        m.addRow(new Object[]{ s.getSlot_id(), s.getVehicletandp(),
                                               s.getNumber_of_slot(), s.getLevel_number() });
                    }
                }
            } catch (Exception ex) { showError("Search failed.", ex); }
        }
    }

    /* ===================================================== *
     *  UTIL                                                 *
     * ===================================================== */
    void showError(String msg, Exception ex){
        JOptionPane.showMessageDialog(view,msg+"\n"+ex.getMessage(),
                                      "DB error",JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    /* Called by Add- / Edit-Slot controllers after successful save */
    public void refresh() { loadSlotTable(); }
}
