/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vpms.view;

import java.awt.event.ActionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author being
 */
public class SlotManagementView extends javax.swing.JInternalFrame {

    /**
     * Creates new form SlotManagementView1
     */
    public SlotManagementView() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        jCancelButton = new javax.swing.JButton();
        jEditSlotButton = new javax.swing.JButton();
        deleteSlotButton = new javax.swing.JButton();
        jAddSlotButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        slotTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        searchTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        searchTextField.setText("Search");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        jCancelButton.setBackground(new java.awt.Color(255, 153, 0));
        jCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jEditSlotButton.setBackground(new java.awt.Color(153, 255, 153));
        jEditSlotButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jEditSlotButton.setText("Edit Slot");
        jEditSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditSlotButtonActionPerformed(evt);
            }
        });

        deleteSlotButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteSlotButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteSlotButton.setText("Delete");
        deleteSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSlotButtonActionPerformed(evt);
            }
        });

        jAddSlotButton.setBackground(new java.awt.Color(102, 153, 255));
        jAddSlotButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jAddSlotButton.setText("Add");
        jAddSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddSlotButtonActionPerformed(evt);
            }
        });

        slotTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slot ID", "VehicleTandP", "Number of Slots ", "Level Number  "
            }
        ));
        jScrollPane2.setViewportView(slotTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Slot Management");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Screenshot 2025-06-25 090725.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Screenshot 2025-06-25 091631.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jCancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEditSlotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddSlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSlotButton)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditSlotButton)
                    .addComponent(jAddSlotButton)
                    .addComponent(deleteSlotButton)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jEditSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditSlotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditSlotButtonActionPerformed

    private void deleteSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSlotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSlotButtonActionPerformed

    private void jAddSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddSlotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddSlotButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteSlotButton;
    private javax.swing.JButton jAddSlotButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jEditSlotButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable slotTable;
    // End of variables declaration//GEN-END:variables
    public void addAddButtonListener(ActionListener listener){
        jAddSlotButton.addActionListener(listener);
    }
    public javax.swing.JButton addEditButtonListener(){
        return jEditSlotButton;
    }
    public javax.swing.JButton addDeleteButtonListener(){
        return deleteSlotButton;
    }
    public javax.swing.JButton addCancelButtonListener(){
        return jCancelButton;
    }
    public javax.swing.JTextField addSearchButtonListener(){
        return searchTextField;
    }
    public javax.swing.JTable getSlotTable(){
        return slotTable;
    }
    public javax.swing.JTextField getSearchText(){
        return searchTextField;
    }
}
