/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vpms.view;

/**
 *
 * @author being
 */
public class StaffDashboardContentView extends javax.swing.JInternalFrame {

    /**
     * Creates new form StaffDashboardContentView
     */
    public StaffDashboardContentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardUpperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        parkingExitIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ExitParkingIDCheckButton = new javax.swing.JButton();
        tabLevels = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        dashboardUpperPanel.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        parkingExitIdTextField.setToolTipText("");
        parkingExitIdTextField.setName(""); // NOI18N

        jLabel2.setText("Exit Parking ID:");

        ExitParkingIDCheckButton.setBackground(new java.awt.Color(255, 204, 102));
        ExitParkingIDCheckButton.setText("Check");
        ExitParkingIDCheckButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 204, 0), null, new java.awt.Color(204, 51, 255)));

        javax.swing.GroupLayout dashboardUpperPanelLayout = new javax.swing.GroupLayout(dashboardUpperPanel);
        dashboardUpperPanel.setLayout(dashboardUpperPanelLayout);
        dashboardUpperPanelLayout.setHorizontalGroup(
            dashboardUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardUpperPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parkingExitIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitParkingIDCheckButton)
                .addGap(10, 10, 10))
        );
        dashboardUpperPanelLayout.setVerticalGroup(
            dashboardUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardUpperPanelLayout.createSequentialGroup()
                .addGroup(dashboardUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardUpperPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(dashboardUpperPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(dashboardUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingExitIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(ExitParkingIDCheckButton))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel3.setText("Avilable");
        jPanel1.add(jLabel3);

        jLabel4.setText("Parked");
        jPanel1.add(jLabel4);

        jLabel5.setText("Reserved");
        jPanel1.add(jLabel5);

        tabLevels.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardUpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tabLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboardUpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(tabLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitParkingIDCheckButton;
    private javax.swing.JPanel dashboardUpperPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField parkingExitIdTextField;
    private javax.swing.JTabbedPane tabLevels;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTabbedPane getTabLevels() {
        return tabLevels;
    }

}
